verbose: false

pprof:
  bind: 0.0.0.0:6060

input_redis:
  enabled: true
  bind: 0.0.0.0:6379
  multi: false
  pipeline:
    logtube:
      time_offset: -8
    mysql:
      error_ignore_levels:
        - note

input_sptp:
  enabled: true
  bind: 0.0.0.0:9921

topics:
  keyword_required:
    - info
  ignored:
    - debug
  priors:
    - error

queue:
  dir: /var/lib/logtubed
  name: logtube
  sync_every: 1000

output_es:
  enabled: true
  urls:
    - http://127.0.0.1:9200
  batch_size: 100
  #concurrency: 3

output_local:
  enabled: false
  dir: /var/log/logtube-logs
