[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.1.29"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/redcon"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.9.1"

[[constraint]]
  name = "github.com/juju/ratelimit"
  version = "1.0.1"
